### ISSUE TITLE
generate_jwt issue

### ISSUE THREAD

**Issue by nyue** [athera-io/athera-python#13]
Using the current head and update module/package layout, I am getting the following errors both on Windows and OS X

Traceback (most recent call last):
  File "generate_jwt.py", line 12, in <module>
    from athera.auth.oauth_client import OAuthClient
ModuleNotFoundError: No module named 'athera'

If I run python interactively and execute the "from athera.auth.oauth_client import OAuthClient" on the python interactive session, it works fine.

Cheers

**Comment by sipickles** [comment]
Hi, 

When you launch in an interactive session, I believe the current working directory is added to the python path.

To do the same when running generate_jwt.py, set the python path first to point to your checkout:

```
export PYTHONPATH=<path_to_athera_python_checkout>
python generate_jwt.py
```

Does that help?

**Comment by nyue** [comment]
Yup. It works. Thanks.
